#!/usr/bin/env bash
(( __CONFIG_INCLUDED__ )) && return
__CONFIG_INCLUDED__=1

source ./scripts/include/node

# Make all of our configuration values available as environment variables.
vars=$(babel-node -e "
  const config = require('./config');
  console.log(config.stringifyForShell(config.current));
")

set -a
eval $vars
set +a
