import { BaseComponent } from '../components';

export default class Splash extends BaseComponent {

  render() {
    return (
      <div>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
        <p>Ohai</p>
      </div>
    );
  }

}
