#!/usr/bin/env bash
set -e
source ./scripts/include/config
source ./scripts/include/node

readonly OUTPUT_DIR="${config_buildDir}/${config_variant}"

# It doesn't make sense to have reloading enabled when building static assets.
config_watch=0

rm -rf "${OUTPUT_DIR}"
webpack --config ./config/webpack/index.babel.js

echo
echo "Built project to ${OUTPUT_DIR}"
echo
