#!/usr/bin/env bash
set -e
source ./scripts/include/config
source ./scripts/include/node

# It doesn't make sense to have reloading enabled when building static assets.
config_watch=0

rm -rf "${config_buildDir}"
webpack --config ./config/webpack/es5
cp src/serviceWorker.js "${config_buildDir}"/serviceWorker.js

echo
echo "Built project to ${config_buildDir}"
echo
