#!/usr/bin/env bash
set -e
source ./scripts/include/config

if [[ "${config_firebaseProject}" == "" ]]; then
  echo "firebaseProject is not configured for this variant (${config_variant})"
  exit 1
fi

./scripts/build

firebase --non-interactive deploy \
  --project "${config_firebaseProject}" \
  --public "build/${config_variant}" \
  --message $(git rev-parse HEAD)
