#!/usr/bin/env bash
set -e

# Until the next version is cut
if [[ ! -d ./node_modules/react-web-animation/lib ]]; then
  cd ./node_modules/react-web-animation
  npm install --ignore-scripts
  npm run build:lib
  cd ../..
fi
