#!/usr/bin/env bash
set -e
source ./scripts/include/node

FILES=("${@}")
if [[ "${#FILES[@]}" = "0" ]]; then
  FILES+=($(find config -name "*.js"))
  FILES+=($(find src -name "*.js"))
  FILES+=($(find src -name "*.jsx"))
fi

eslint "${FILES[@]}"
